In [2]:
import pandas as pd
import numpy as np

train_df = pd.read_csv(
    "../data/raw/ChurnZero_dataset_v1.csv"
)

test_df = pd.read_csv(
    "../data/raw/ChurnZero_test_v1.csv"
)

print(train_df.shape)
print(test_df.shape)

train_df.head()

(8101, 98)
(2026, 97)

,customer_id,churn,age,gender,marital_status,education_level,dependent_count,occupation_type,annual_income,income_band,...,discount_or_fee_waiver_received,competitor_bank_offer_awareness,customer_feedback_sentiment,monthly_income_estimate,credit_utilization_3m_avg,credit_utilization_6m_avg,avg_quarterly_balance,total_digital_logins,debt_to_income_ratio,digital_engagement_index
0,133001,0,36,Female,Married,Unknown,0,Salaried,22256,Low,...,0,Not Aware,Positive,1663,0.839,0.721,28420.0,33,0.0000,55.6
1,133002,1,44,Male,Single,High School,3,Homemaker,66481,Middle,...,1,High,Positive,4979,0.009,0.000,11501.0,19,0.0000,54.5
2,133003,0,46,Male,Married,High School,2,Salaried,98955,Upper-Middle,...,0,Low,Positive,8716,0.104,0.169,11619.0,31,0.0000,43.0
3,133004,0,36,Female,Married,Graduate,2,Retired,26735,Low,...,0,Medium,Neutral,2177,0.438,0.439,26458.0,29,0.5135,57.2
4,133005,0,50,Male,Single,Graduate,1,Salaried,165387,High,...,1,Low,Positive,15401,0.061,0.039,23938.0,22,0.2289,56.1

In [3]:
train_df.info()
train_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 8101 entries, 0 to 8100
Data columns (total 98 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   customer_id                             8101 non-null   int64
 1   churn                                   8101 non-null   int64
 2   age                                     8101 non-null   int64
 3   gender                                  8101 non-null   str
 4   marital_status                          8101 non-null   str
 5   education_level                         8101 non-null   str
 6   dependent_count                         8101 non-null   int64
 7   occupation_type                         8101 non-null   str
 8   annual_income                           8101 non-null   int64
 9   income_band                             8101 non-null   str
 10  income_category                         8101 non-null   str
 11  city_tier                               8101 non-null   str
 12  region                                  8101 non-null   str
 13  customer_segment                        8101 non-null   str
 14  tenure_months                           8101 non-null   int64
 15  onboarding_channel                      8101 non-null   str
 16  relationship_type                       8101 non-null   str
 17  number_of_products                      8101 non-null   int64
 18  primary_account_type                    8101 non-null   str
 19  card_category                           8101 non-null   str
 20  customer_lifetime_value                 8101 non-null   float64
 21  loyalty_program_member                  8101 non-null   int64
 22  referral_count                          8101 non-null   int64
 23  last_contacted_days                     8101 non-null   int64
 24  relationship_manager_assigned           8101 non-null   int64
 25  avg_monthly_balance                     8101 non-null   float64
 26  current_balance                         8101 non-null   float64
 27  balance_decline_percentage              8101 non-null   float64
 28  monthly_transaction_count               8101 non-null   int64
 29  monthly_transaction_value               8101 non-null   float64
 30  cash_withdrawal_count                   8101 non-null   int64
 31  upi_transaction_count                   8101 non-null   int64
 32  debit_card_transaction_count            8101 non-null   int64
 33  net_banking_transaction_count           8101 non-null   int64
 34  account_inactive_days                   8101 non-null   int64
 35  total_trans_amt                         8101 non-null   int64
 36  total_trans_count                       8101 non-null   int64
 37  total_amt_chng_q4_q1                    8101 non-null   float64
 38  total_ct_chng_q4_q1                     8101 non-null   float64
 39  avg_open_to_buy                         8101 non-null   float64
 40  total_revolving_bal                     8101 non-null   int64
 41  savings_account_flag                    8101 non-null   int64
 42  current_account_flag                    8101 non-null   int64
 43  credit_card_flag                        8101 non-null   int64
 44  personal_loan_flag                      8101 non-null   int64
 45  home_loan_flag                          8101 non-null   int64
 46  auto_loan_flag                          8101 non-null   int64
 47  fixed_deposit_flag                      8101 non-null   int64
 48  investment_product_flag                 8101 non-null   int64
 49  insurance_product_flag                  8101 non-null   int64
 50  demat_account_flag                      8101 non-null   int64
 51  credit_card_limit                       8101 non-null   int64
 52  credit_card_spend                       8101 non-null   float64
 53  credit_utilization_ratio                8101 non-null   float64
 54  minimum_due_paid_flag                   8101 non-null   int64
 55  late_credit_card_payment_count          8101 non-null   int64
 56  loan_outstanding_amount                 8101 non-null   float64
 57  emi_amount                              8101 non-null   float64
 58  emi_payment_delay_count                 8101 non-null   int64
 59  loan_default_risk_score                 8101 non-null   float64
 60  prepayment_flag                         8101 non-null   int64
 61  mobile_app_login_count                  8101 non-null   int64
 62  website_login_count                     8101 non-null   int64
 63  digital_transaction_ratio               8101 non-null   float64
 64  last_login_days                         8101 non-null   int64
 65  failed_login_count                      8101 non-null   int64
 66  app_rating_given                        3560 non-null   float64
 67  paperless_statement_enabled             8101 non-null   int64
 68  digital_service_usage_score             8101 non-null   float64
 69  mobile_banking_active_flag              8101 non-null   int64
 70  email_open_rate                         8101 non-null   float64
 71  total_complaints                        8101 non-null   int64
 72  complaint_resolution_time               8101 non-null   int64
 73  unresolved_complaint_count              8101 non-null   int64
 74  branch_visit_count                      8101 non-null   int64
 75  call_center_interaction_count           8101 non-null   int64
 76  relationship_manager_interaction_count  8101 non-null   int64
 77  service_request_count                   8101 non-null   int64
 78  escalation_count                        8101 non-null   int64
 79  satisfaction_score                      8101 non-null   float64
 80  nps_score                               8101 non-null   int64
 81  campaign_received_count                 8101 non-null   int64
 82  campaign_response_count                 8101 non-null   int64
 83  cross_sell_offer_count                  8101 non-null   int64
 84  upsell_offer_count                      8101 non-null   int64
 85  retention_offer_received                8101 non-null   int64
 86  retention_offer_accepted                8101 non-null   int64
 87  last_campaign_response_days             8101 non-null   int64
 88  discount_or_fee_waiver_received         8101 non-null   int64
 89  competitor_bank_offer_awareness         8101 non-null   str
 90  customer_feedback_sentiment             8101 non-null   str
 91  monthly_income_estimate                 8101 non-null   int64
 92  credit_utilization_3m_avg               8101 non-null   float64
 93  credit_utilization_6m_avg               8101 non-null   float64
 94  avg_quarterly_balance                   8101 non-null   float64
 95  total_digital_logins                    8101 non-null   int64
 96  debt_to_income_ratio                    8101 non-null   float64
 97  digital_engagement_index                8101 non-null   float64
dtypes: float64(23), int64(60), str(15)
memory usage: 6.9 MB

,customer_id,churn,age,dependent_count,annual_income,tenure_months,number_of_products,customer_lifetime_value,loyalty_program_member,referral_count,...,retention_offer_accepted,last_campaign_response_days,discount_or_fee_waiver_received,monthly_income_estimate,credit_utilization_3m_avg,credit_utilization_6m_avg,avg_quarterly_balance,total_digital_logins,debt_to_income_ratio,digital_engagement_index
count,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,...,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000,8101.000000
mean,137051.000000,0.160721,46.390199,2.349093,60052.874583,36.005555,3.810023,14102.415556,0.542772,1.046537,...,0.100358,54.956795,0.178867,5130.857672,0.261066,0.281485,45642.588940,28.060363,0.415710,51.773250
std,2338.701598,0.367296,7.985385,1.297993,35422.472020,7.934351,1.554787,10603.985218,0.498198,1.076428,...,0.300495,62.794492,0.383264,3368.244723,0.254869,0.215617,39075.635887,6.394283,0.702155,8.781389
min,133001.000000,0.000000,26.000000,0.000000,18000.000000,13.000000,1.000000,733.480000,0.000000,0.000000,...,0.000000,1.000000,0.000000,1000.000000,0.000000,0.000000,2781.000000,6.000000,0.000000,26.300000
25%,135026.000000,0.000000,41.000000,1.000000,31813.000000,32.000000,3.000000,6563.310000,0.000000,0.000000,...,0.000000,14.000000,0.000000,2700.000000,0.036000,0.105000,20729.000000,24.000000,0.000000,44.300000
50%,137051.000000,0.000000,46.000000,2.000000,51592.000000,36.000000,4.000000,11166.440000,1.000000,1.000000,...,0.000000,34.000000,0.000000,4360.000000,0.169000,0.218000,34888.000000,28.000000,0.163300,53.600000
75%,139076.000000,0.000000,52.000000,3.000000,76910.000000,40.000000,5.000000,18585.960000,1.000000,2.000000,...,0.000000,73.000000,0.000000,6622.000000,0.471000,0.450000,57919.000000,32.000000,0.519000,58.600000
max,141101.000000,1.000000,73.000000,5.000000,241318.000000,56.000000,6.000000,88861.820000,1.000000,7.000000,...,1.000000,365.000000,1.000000,31267.000000,0.961000,0.935000,501402.000000,50.000000,5.000000,75.100000

In [4]:
train_df.shape

(8101, 98)

In [5]:
train_df.head()

,customer_id,churn,age,gender,marital_status,education_level,dependent_count,occupation_type,annual_income,income_band,...,discount_or_fee_waiver_received,competitor_bank_offer_awareness,customer_feedback_sentiment,monthly_income_estimate,credit_utilization_3m_avg,credit_utilization_6m_avg,avg_quarterly_balance,total_digital_logins,debt_to_income_ratio,digital_engagement_index
0,133001,0,36,Female,Married,Unknown,0,Salaried,22256,Low,...,0,Not Aware,Positive,1663,0.839,0.721,28420.0,33,0.0000,55.6
1,133002,1,44,Male,Single,High School,3,Homemaker,66481,Middle,...,1,High,Positive,4979,0.009,0.000,11501.0,19,0.0000,54.5
2,133003,0,46,Male,Married,High School,2,Salaried,98955,Upper-Middle,...,0,Low,Positive,8716,0.104,0.169,11619.0,31,0.0000,43.0
3,133004,0,36,Female,Married,Graduate,2,Retired,26735,Low,...,0,Medium,Neutral,2177,0.438,0.439,26458.0,29,0.5135,57.2
4,133005,0,50,Male,Single,Graduate,1,Salaried,165387,High,...,1,Low,Positive,15401,0.061,0.039,23938.0,22,0.2289,56.1

In [6]:
train_df.isnull().sum().sort_values(
    ascending=False
).head(30)

app_rating_given                 4541
customer_id                         0
age                                 0
gender                              0
marital_status                      0
education_level                     0
dependent_count                     0
occupation_type                     0
annual_income                       0
income_band                         0
income_category                     0
city_tier                           0
region                              0
customer_segment                    0
tenure_months                       0
onboarding_channel                  0
relationship_type                   0
number_of_products                  0
primary_account_type                0
card_category                       0
customer_lifetime_value             0
loyalty_program_member              0
referral_count                      0
last_contacted_days                 0
relationship_manager_assigned       0
avg_monthly_balance                 0
current_balance                     0
balance_decline_percentage          0
monthly_transaction_count           0
monthly_transaction_value           0
dtype: int64

In [7]:
train_df.columns.tolist()

['customer_id',
 'churn',
 'age',
 'gender',
 'marital_status',
 'education_level',
 'dependent_count',
 'occupation_type',
 'annual_income',
 'income_band',
 'income_category',
 'city_tier',
 'region',
 'customer_segment',
 'tenure_months',
 'onboarding_channel',
 'relationship_type',
 'number_of_products',
 'primary_account_type',
 'card_category',
 'customer_lifetime_value',
 'loyalty_program_member',
 'referral_count',
 'last_contacted_days',
 'relationship_manager_assigned',
 'avg_monthly_balance',
 'current_balance',
 'balance_decline_percentage',
 'monthly_transaction_count',
 'monthly_transaction_value',
 'cash_withdrawal_count',
 'upi_transaction_count',
 'debit_card_transaction_count',
 'net_banking_transaction_count',
 'account_inactive_days',
 'total_trans_amt',
 'total_trans_count',
 'total_amt_chng_q4_q1',
 'total_ct_chng_q4_q1',
 'avg_open_to_buy',
 'total_revolving_bal',
 'savings_account_flag',
 'current_account_flag',
 'credit_card_flag',
 'personal_loan_flag',
 'home_loan_flag',
 'auto_loan_flag',
 'fixed_deposit_flag',
 'investment_product_flag',
 'insurance_product_flag',
 'demat_account_flag',
 'credit_card_limit',
 'credit_card_spend',
 'credit_utilization_ratio',
 'minimum_due_paid_flag',
 'late_credit_card_payment_count',
 'loan_outstanding_amount',
 'emi_amount',
 'emi_payment_delay_count',
 'loan_default_risk_score',
 'prepayment_flag',
 'mobile_app_login_count',
 'website_login_count',
 'digital_transaction_ratio',
 'last_login_days',
 'failed_login_count',
 'app_rating_given',
 'paperless_statement_enabled',
 'digital_service_usage_score',
 'mobile_banking_active_flag',
 'email_open_rate',
 'total_complaints',
 'complaint_resolution_time',
 'unresolved_complaint_count',
 'branch_visit_count',
 'call_center_interaction_count',
 'relationship_manager_interaction_count',
 'service_request_count',
 'escalation_count',
 'satisfaction_score',
 'nps_score',
 'campaign_received_count',
 'campaign_response_count',
 'cross_sell_offer_count',
 'upsell_offer_count',
 'retention_offer_received',
 'retention_offer_accepted',
 'last_campaign_response_days',
 'discount_or_fee_waiver_received',
 'competitor_bank_offer_awareness',
 'customer_feedback_sentiment',
 'monthly_income_estimate',
 'credit_utilization_3m_avg',
 'credit_utilization_6m_avg',
 'avg_quarterly_balance',
 'total_digital_logins',
 'debt_to_income_ratio',
 'digital_engagement_index']

In [8]:
train_df["churn"].value_counts()

churn
0    6799
1    1302
Name: count, dtype: int64

In [9]:
categorical_cols = train_df.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_cols = train_df.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("Categorical Columns:")
print(categorical_cols)

print("\nNumerical Columns:")
print(numerical_cols)

Categorical Columns:
['gender', 'marital_status', 'education_level', 'occupation_type', 'income_band', 'income_category', 'city_tier', 'region', 'customer_segment', 'onboarding_channel', 'relationship_type', 'primary_account_type', 'card_category', 'competitor_bank_offer_awareness', 'customer_feedback_sentiment']

Numerical Columns:
['customer_id', 'churn', 'age', 'dependent_count', 'annual_income', 'tenure_months', 'number_of_products', 'customer_lifetime_value', 'loyalty_program_member', 'referral_count', 'last_contacted_days', 'relationship_manager_assigned', 'avg_monthly_balance', 'current_balance', 'balance_decline_percentage', 'monthly_transaction_count', 'monthly_transaction_value', 'cash_withdrawal_count', 'upi_transaction_count', 'debit_card_transaction_count', 'net_banking_transaction_count', 'account_inactive_days', 'total_trans_amt', 'total_trans_count', 'total_amt_chng_q4_q1', 'total_ct_chng_q4_q1', 'avg_open_to_buy', 'total_revolving_bal', 'savings_account_flag', 'current_account_flag', 'credit_card_flag', 'personal_loan_flag', 'home_loan_flag', 'auto_loan_flag', 'fixed_deposit_flag', 'investment_product_flag', 'insurance_product_flag', 'demat_account_flag', 'credit_card_limit', 'credit_card_spend', 'credit_utilization_ratio', 'minimum_due_paid_flag', 'late_credit_card_payment_count', 'loan_outstanding_amount', 'emi_amount', 'emi_payment_delay_count', 'loan_default_risk_score', 'prepayment_flag', 'mobile_app_login_count', 'website_login_count', 'digital_transaction_ratio', 'last_login_days', 'failed_login_count', 'app_rating_given', 'paperless_statement_enabled', 'digital_service_usage_score', 'mobile_banking_active_flag', 'email_open_rate', 'total_complaints', 'complaint_resolution_time', 'unresolved_complaint_count', 'branch_visit_count', 'call_center_interaction_count', 'relationship_manager_interaction_count', 'service_request_count', 'escalation_count', 'satisfaction_score', 'nps_score', 'campaign_received_count', 'campaign_response_count', 'cross_sell_offer_count', 'upsell_offer_count', 'retention_offer_received', 'retention_offer_accepted', 'last_campaign_response_days', 'discount_or_fee_waiver_received', 'monthly_income_estimate', 'credit_utilization_3m_avg', 'credit_utilization_6m_avg', 'avg_quarterly_balance', 'total_digital_logins', 'debt_to_income_ratio', 'digital_engagement_index']

C:\Users\Aishwarya\AppData\Local\Temp\ipykernel_22204\181531354.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train_df.select_dtypes(

In [10]:
train_df.columns.tolist()

['customer_id',
 'churn',
 'age',
 'gender',
 'marital_status',
 'education_level',
 'dependent_count',
 'occupation_type',
 'annual_income',
 'income_band',
 'income_category',
 'city_tier',
 'region',
 'customer_segment',
 'tenure_months',
 'onboarding_channel',
 'relationship_type',
 'number_of_products',
 'primary_account_type',
 'card_category',
 'customer_lifetime_value',
 'loyalty_program_member',
 'referral_count',
 'last_contacted_days',
 'relationship_manager_assigned',
 'avg_monthly_balance',
 'current_balance',
 'balance_decline_percentage',
 'monthly_transaction_count',
 'monthly_transaction_value',
 'cash_withdrawal_count',
 'upi_transaction_count',
 'debit_card_transaction_count',
 'net_banking_transaction_count',
 'account_inactive_days',
 'total_trans_amt',
 'total_trans_count',
 'total_amt_chng_q4_q1',
 'total_ct_chng_q4_q1',
 'avg_open_to_buy',
 'total_revolving_bal',
 'savings_account_flag',
 'current_account_flag',
 'credit_card_flag',
 'personal_loan_flag',
 'home_loan_flag',
 'auto_loan_flag',
 'fixed_deposit_flag',
 'investment_product_flag',
 'insurance_product_flag',
 'demat_account_flag',
 'credit_card_limit',
 'credit_card_spend',
 'credit_utilization_ratio',
 'minimum_due_paid_flag',
 'late_credit_card_payment_count',
 'loan_outstanding_amount',
 'emi_amount',
 'emi_payment_delay_count',
 'loan_default_risk_score',
 'prepayment_flag',
 'mobile_app_login_count',
 'website_login_count',
 'digital_transaction_ratio',
 'last_login_days',
 'failed_login_count',
 'app_rating_given',
 'paperless_statement_enabled',
 'digital_service_usage_score',
 'mobile_banking_active_flag',
 'email_open_rate',
 'total_complaints',
 'complaint_resolution_time',
 'unresolved_complaint_count',
 'branch_visit_count',
 'call_center_interaction_count',
 'relationship_manager_interaction_count',
 'service_request_count',
 'escalation_count',
 'satisfaction_score',
 'nps_score',
 'campaign_received_count',
 'campaign_response_count',
 'cross_sell_offer_count',
 'upsell_offer_count',
 'retention_offer_received',
 'retention_offer_accepted',
 'last_campaign_response_days',
 'discount_or_fee_waiver_received',
 'competitor_bank_offer_awareness',
 'customer_feedback_sentiment',
 'monthly_income_estimate',
 'credit_utilization_3m_avg',
 'credit_utilization_6m_avg',
 'avg_quarterly_balance',
 'total_digital_logins',
 'debt_to_income_ratio',
 'digital_engagement_index']

In [11]:
target_col = "churn"

id_cols = [
    "customer_id"
]

drop_cols = [
]

In [12]:
categorical_cols = train_df.select_dtypes(
    include=["object"]
).columns.tolist()

categorical_cols

C:\Users\Aishwarya\AppData\Local\Temp\ipykernel_22204\283329905.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train_df.select_dtypes(

['gender',
 'marital_status',
 'education_level',
 'occupation_type',
 'income_band',
 'income_category',
 'city_tier',
 'region',
 'customer_segment',
 'onboarding_channel',
 'relationship_type',
 'primary_account_type',
 'card_category',
 'competitor_bank_offer_awareness',
 'customer_feedback_sentiment']

In [13]:
numerical_cols = train_df.select_dtypes(
    exclude=["object"]
).columns.tolist()

numerical_cols

['customer_id',
 'churn',
 'age',
 'dependent_count',
 'annual_income',
 'tenure_months',
 'number_of_products',
 'customer_lifetime_value',
 'loyalty_program_member',
 'referral_count',
 'last_contacted_days',
 'relationship_manager_assigned',
 'avg_monthly_balance',
 'current_balance',
 'balance_decline_percentage',
 'monthly_transaction_count',
 'monthly_transaction_value',
 'cash_withdrawal_count',
 'upi_transaction_count',
 'debit_card_transaction_count',
 'net_banking_transaction_count',
 'account_inactive_days',
 'total_trans_amt',
 'total_trans_count',
 'total_amt_chng_q4_q1',
 'total_ct_chng_q4_q1',
 'avg_open_to_buy',
 'total_revolving_bal',
 'savings_account_flag',
 'current_account_flag',
 'credit_card_flag',
 'personal_loan_flag',
 'home_loan_flag',
 'auto_loan_flag',
 'fixed_deposit_flag',
 'investment_product_flag',
 'insurance_product_flag',
 'demat_account_flag',
 'credit_card_limit',
 'credit_card_spend',
 'credit_utilization_ratio',
 'minimum_due_paid_flag',
 'late_credit_card_payment_count',
 'loan_outstanding_amount',
 'emi_amount',
 'emi_payment_delay_count',
 'loan_default_risk_score',
 'prepayment_flag',
 'mobile_app_login_count',
 'website_login_count',
 'digital_transaction_ratio',
 'last_login_days',
 'failed_login_count',
 'app_rating_given',
 'paperless_statement_enabled',
 'digital_service_usage_score',
 'mobile_banking_active_flag',
 'email_open_rate',
 'total_complaints',
 'complaint_resolution_time',
 'unresolved_complaint_count',
 'branch_visit_count',
 'call_center_interaction_count',
 'relationship_manager_interaction_count',
 'service_request_count',
 'escalation_count',
 'satisfaction_score',
 'nps_score',
 'campaign_received_count',
 'campaign_response_count',
 'cross_sell_offer_count',
 'upsell_offer_count',
 'retention_offer_received',
 'retention_offer_accepted',
 'last_campaign_response_days',
 'discount_or_fee_waiver_received',
 'monthly_income_estimate',
 'credit_utilization_3m_avg',
 'credit_utilization_6m_avg',
 'avg_quarterly_balance',
 'total_digital_logins',
 'debt_to_income_ratio',
 'digital_engagement_index']

In [14]:
feature_cols = [
    col for col in train_df.columns
    if col not in [target_col] + id_cols
]

len(feature_cols)

96

# Advanced Feature Engineering

In [15]:
train_df["income_per_dependent"] = (
    train_df["annual_income"] /
    (train_df["dependent_count"] + 1)
)

train_df["products_per_tenure"] = (
    train_df["number_of_products"] /
    (train_df["tenure_months"] + 1)
)

train_df["engagement_score"] = (
    train_df["digital_engagement_index"] *
    train_df["total_digital_logins"]
)

train_df["relationship_depth_score"] = (
    train_df["number_of_products"] *
    train_df["tenure_months"]
)

train_df["high_value_customer"] = (
    train_df["customer_lifetime_value"] >
    train_df["customer_lifetime_value"].median()
).astype(int)

train_df["inactive_high_value"] = (
    (
        train_df["high_value_customer"] == 1
    ) &
    (
        train_df["digital_engagement_index"] <
        train_df["digital_engagement_index"].median()
    )
).astype(int)

train_df["financial_stress_score"] = (
    train_df["debt_to_income_ratio"] *
    (
        1 /
        (train_df["annual_income"] + 1)
    )
)

train_df["loyalty_index"] = (
    train_df["tenure_months"] *
    train_df["loyalty_program_member"]
)

train_df.head()

,customer_id,churn,age,gender,marital_status,education_level,dependent_count,occupation_type,annual_income,income_band,...,debt_to_income_ratio,digital_engagement_index,income_per_dependent,products_per_tenure,engagement_score,relationship_depth_score,high_value_customer,inactive_high_value,financial_stress_score,loyalty_index
0,133001,0,36,Female,Married,Unknown,0,Salaried,22256,Low,...,0.0000,55.6,22256.000000,0.160000,1834.8,96,0,0,0.000000,0
1,133002,1,44,Male,Single,High School,3,Homemaker,66481,Middle,...,0.0000,54.5,16620.250000,0.135135,1035.5,180,0,0,0.000000,36
2,133003,0,46,Male,Married,High School,2,Salaried,98955,Upper-Middle,...,0.0000,43.0,32985.000000,0.193548,1333.0,180,1,1,0.000000,0
3,133004,0,36,Female,Married,Graduate,2,Retired,26735,Low,...,0.5135,57.2,8911.666667,0.120000,1658.8,72,0,0,0.000019,24
4,133005,0,50,Male,Single,Graduate,1,Salaried,165387,High,...,0.2289,56.1,82693.500000,0.097561,1234.2,160,1,0,0.000001,0

In [16]:
train_df.shape

(8101, 106)

# Train Validation Split

In [17]:
from sklearn.model_selection import train_test_split

possible_leakage = [
    "retention_offer_received",
    "retention_offer_accepted",
    "discount_or_fee_waiver_received",
    "unresolved_complaint_count",
    "complaint_resolution_time",
    "last_campaign_response_days",
    "service_request_count",
    "escalation_count",
    "account_inactive_days",
    "last_login_days"
]

X = train_df.drop(
    columns=[target_col] + possible_leakage + id_cols + drop_cols
)

y = train_df[target_col]

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print(X_train.shape)
print(X_valid.shape)

(6480, 94)
(1621, 94)

In [18]:
print(X.columns)

Index(['age', 'gender', 'marital_status', 'education_level', 'dependent_count',
       'occupation_type', 'annual_income', 'income_band', 'income_category',
       'city_tier', 'region', 'customer_segment', 'tenure_months',
       'onboarding_channel', 'relationship_type', 'number_of_products',
       'primary_account_type', 'card_category', 'customer_lifetime_value',
       'loyalty_program_member', 'referral_count', 'last_contacted_days',
       'relationship_manager_assigned', 'avg_monthly_balance',
       'current_balance', 'balance_decline_percentage',
       'monthly_transaction_count', 'monthly_transaction_value',
       'cash_withdrawal_count', 'upi_transaction_count',
       'debit_card_transaction_count', 'net_banking_transaction_count',
       'total_trans_amt', 'total_trans_count', 'total_amt_chng_q4_q1',
       'total_ct_chng_q4_q1', 'avg_open_to_buy', 'total_revolving_bal',
       'savings_account_flag', 'current_account_flag', 'credit_card_flag',
       'personal_loan_flag', 'home_loan_flag', 'auto_loan_flag',
       'fixed_deposit_flag', 'investment_product_flag',
       'insurance_product_flag', 'demat_account_flag', 'credit_card_limit',
       'credit_card_spend', 'credit_utilization_ratio',
       'minimum_due_paid_flag', 'late_credit_card_payment_count',
       'loan_outstanding_amount', 'emi_amount', 'emi_payment_delay_count',
       'loan_default_risk_score', 'prepayment_flag', 'mobile_app_login_count',
       'website_login_count', 'digital_transaction_ratio',
       'failed_login_count', 'app_rating_given', 'paperless_statement_enabled',
       'digital_service_usage_score', 'mobile_banking_active_flag',
       'email_open_rate', 'total_complaints', 'branch_visit_count',
       'call_center_interaction_count',
       'relationship_manager_interaction_count', 'satisfaction_score',
       'nps_score', 'campaign_received_count', 'campaign_response_count',
       'cross_sell_offer_count', 'upsell_offer_count',
       'competitor_bank_offer_awareness', 'customer_feedback_sentiment',
       'monthly_income_estimate', 'credit_utilization_3m_avg',
       'credit_utilization_6m_avg', 'avg_quarterly_balance',
       'total_digital_logins', 'debt_to_income_ratio',
       'digital_engagement_index', 'income_per_dependent',
       'products_per_tenure', 'engagement_score', 'relationship_depth_score',
       'high_value_customer', 'inactive_high_value', 'financial_stress_score',
       'loyalty_index'],
      dtype='str')

In [19]:
print("churn" in X.columns)

False

In [20]:
categorical_cols = X_train.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_cols = X_train.select_dtypes(
    exclude=["object"]
).columns.tolist()

print(len(categorical_cols))
print(len(numerical_cols))

15
79

C:\Users\Aishwarya\AppData\Local\Temp\ipykernel_22204\400345636.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train.select_dtypes(

# Preprocessing Pipeline

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler
)

numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numerical_cols
        ),
        (
            "cat",
            categorical_transformer,
            categorical_cols
        )
    ]
)

# Baseline Logistic Regression Model

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

baseline_model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced",
                random_state=42
            )
        )
    ]
)

baseline_model.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'dependent_count',
                                                   'annual_income',
                                                   'tenure_months',
                                                   'number_of_products',
                                                   'customer_lifetime_value',
                                                   'loyalty_program_member',
                                                   'referral_count',
                                                   'last_contacted_days',
                                                   'relationship_manage...
                                                  ['gender', 'marital_status',
                                                   'education_level',
                                                   'occupation_type',
                                                   'income_band',
                                                   'income_category',
                                                   'city_tier', 'region',
                                                   'customer_segment',
                                                   'onboarding_channel',
                                                   'relationship_type',
                                                   'primary_account_type',
                                                   'card_category',
                                                   'competitor_bank_offer_awareness',
                                                   'customer_feedback_sentiment'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [23]:
baseline_preds = baseline_model.predict(
    X_valid
)

baseline_probs = baseline_model.predict_proba(
    X_valid
)[:, 1]

In [24]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

print(
    classification_report(
        y_valid,
        baseline_preds
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        baseline_preds
    )
)

print(
    "\nROC-AUC:",
    roc_auc_score(
        y_valid,
        baseline_probs
    )
)

print(
    "\nPR-AUC:",
    average_precision_score(
        y_valid,
        baseline_probs
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1360
           1       1.00      0.99      0.99       261

    accuracy                           1.00      1621
   macro avg       1.00      0.99      1.00      1621
weighted avg       1.00      1.00      1.00      1621


Confusion Matrix:
[[1359    1]
 [   3  258]]

ROC-AUC: 0.9995774171737661

PR-AUC: 0.998472922303206

In [25]:
for col in train_df.columns:

    if train_df[col].nunique() < 10:

        print("\n")
        print(col)

        print(
            train_df[col].value_counts()
        )

churn
churn
0    6799
1    1302
Name: count, dtype: int64


gender
gender
Female    4272
Male      3829
Name: count, dtype: int64


marital_status
marital_status
Married     3755
Single      3142
Unknown      605
Divorced     599
Name: count, dtype: int64


education_level
education_level
Graduate         2482
High School      1650
Unknown          1207
Uneducated       1183
College           796
Post-Graduate     427
Doctorate         356
Name: count, dtype: int64


dependent_count
dependent_count
3    2205
2    2119
1    1463
4    1251
0     721
5     342
Name: count, dtype: int64


occupation_type
occupation_type
Salaried          3481
Self-Employed     1631
Business Owner    1299
Retired            840
Homemaker          436
Student            414
Name: count, dtype: int64


income_band
income_band
Middle          2371
Lower-Middle    2059
Low             1779
Upper-Middle    1372
High             520
Name: count, dtype: int64


income_category
income_category
Less than $40K    2832
$40K - $60K       1450
$80K - $120K      1209
$60K - $80K       1136
Unknown            886
$120K +            588
Name: count, dtype: int64


city_tier
city_tier
Tier 2    3289
Tier 1    2840
Tier 3    1972
Name: count, dtype: int64


region
region
South      1999
North      1814
West       1599
East       1470
Central    1219
Name: count, dtype: int64


customer_segment
customer_segment
Affluent    3398
Mass        2808
HNI         1895
Name: count, dtype: int64


onboarding_channel
onboarding_channel
Branch        2386
Online        2076
Mobile App    1599
DSA           1245
Referral       795
Name: count, dtype: int64


relationship_type
relationship_type
Multi-Product    2854
Savings Only     1998
Lending          1610
Investment       1017
Premium           622
Name: count, dtype: int64


number_of_products
number_of_products
3    1884
5    1534
4    1498
6    1481
2     961
1     743
Name: count, dtype: int64


primary_account_type
primary_account_type
Savings    4445
Current    2044
Salary     1247
NRE/NRO     365
Name: count, dtype: int64


card_category
card_category
Blue        7559
Silver       431
Gold          94
Platinum      17
Name: count, dtype: int64


loyalty_program_member
loyalty_program_member
1    4397
0    3704
Name: count, dtype: int64


referral_count
referral_count
0    3029
1    2768
2    1495
3     584
4     174
5      38
6       9
7       4
Name: count, dtype: int64


relationship_manager_assigned
relationship_manager_assigned
1    4361
0    3740
Name: count, dtype: int64


savings_account_flag
savings_account_flag
1    6874
0    1227
Name: count, dtype: int64


current_account_flag
current_account_flag
0    5082
1    3019
Name: count, dtype: int64


credit_card_flag
credit_card_flag
1    8101
Name: count, dtype: int64


personal_loan_flag
personal_loan_flag
0    5416
1    2685
Name: count, dtype: int64


home_loan_flag
home_loan_flag
0    5995
1    2106
Name: count, dtype: int64


auto_loan_flag
auto_loan_flag
0    6386
1    1715
Name: count, dtype: int64


fixed_deposit_flag
fixed_deposit_flag
0    4775
1    3326
Name: count, dtype: int64


investment_product_flag
investment_product_flag
0    4900
1    3201
Name: count, dtype: int64


insurance_product_flag
insurance_product_flag
1    4131
0    3970
Name: count, dtype: int64


demat_account_flag
demat_account_flag
0    5753
1    2348
Name: count, dtype: int64


minimum_due_paid_flag
minimum_due_paid_flag
1    5872
0    2229
Name: count, dtype: int64


late_credit_card_payment_count
late_credit_card_payment_count
1    3303
0    2045
2    1868
3     646
4     176
5      49
6      10
7       3
9       1
Name: count, dtype: int64


emi_payment_delay_count
emi_payment_delay_count
0    6468
1    1074
2     338
3     150
4      42
5      21
6       4
7       3
8       1
Name: count, dtype: int64


prepayment_flag
prepayment_flag
0    7004
1    1097
Name: count, dtype: int64


failed_login_count
failed_login_count
1    3534
0    2324
2    1677
3     462
4      87
5      13
6       3
7       1
Name: count, dtype: int64


paperless_statement_enabled
paperless_statement_enabled
1    5249
0    2852
Name: count, dtype: int64


mobile_banking_active_flag
mobile_banking_active_flag
1    8100
0       1
Name: count, dtype: int64


total_complaints
total_complaints
1    3060
2    2037
0    1635
3     941
4     313
5      83
6      24
7       7
8       1
Name: count, dtype: int64


unresolved_complaint_count
unresolved_complaint_count
0    7668
1     315
2      99
3      15
4       4
Name: count, dtype: int64


call_center_interaction_count
call_center_interaction_count
3    2712
2    2563
1    1195
4    1114
0     328
5     147
6      42
Name: count, dtype: int64


escalation_count
escalation_count
0    7915
1     167
2      19
Name: count, dtype: int64


campaign_response_count
campaign_response_count
0    6406
1    1474
2     208
3      13
Name: count, dtype: int64


upsell_offer_count
upsell_offer_count
1    2983
0    2938
2    1504
3     514
4     132
5      24
6       5
8       1
Name: count, dtype: int64


retention_offer_received
retention_offer_received
0    6338
1    1763
Name: count, dtype: int64


retention_offer_accepted
retention_offer_accepted
0    7288
1     813
Name: count, dtype: int64


discount_or_fee_waiver_received
discount_or_fee_waiver_received
0    6652
1    1449
Name: count, dtype: int64


competitor_bank_offer_awareness
competitor_bank_offer_awareness
Low          2522
Medium       2150
Not Aware    2105
High         1324
Name: count, dtype: int64


customer_feedback_sentiment
customer_feedback_sentiment
Positive    4590
Neutral     2101
Negative    1410
Name: count, dtype: int64


high_value_customer
high_value_customer
0    4051
1    4050
Name: count, dtype: int64


inactive_high_value
inactive_high_value
0    6177
1    1924
Name: count, dtype: int64

In [ ]:
correlations = train_df.corr(
    numeric_only=True
)["churn"].sort_values(
    ascending=False
)

correlations.head(20)

churn                              1.000000
unresolved_complaint_count         0.494274
balance_decline_percentage         0.455938
complaint_resolution_time          0.448285
last_campaign_response_days        0.404755
emi_payment_delay_count            0.403164
service_request_count              0.392190
last_contacted_days                0.383718
retention_offer_received           0.371955
last_login_days                    0.342650
escalation_count                   0.337508
total_complaints                   0.303294
late_credit_card_payment_count     0.300036
digital_transaction_ratio          0.254789
loan_default_risk_score            0.231309
call_center_interaction_count      0.205486
failed_login_count                 0.192146
discount_or_fee_waiver_received    0.189534
account_inactive_days              0.150891
dependent_count                    0.030940
Name: churn, dtype: float64

: